### ISSUE TITLE
Additional Noise Data

### ISSUE THREAD

**Issue by ycjing** [superlouis/NODE-SELECT#1]
Hi @superlouis @alireza-nasiri 

Thank you for this wonderful work! May I ask how to generate noise data and get the results from Tab. 3 of the paper? I will appreciate your help. Thank you! 

Best,
Yongcheng

**Comment by superlouis** [comment]
Hey @ycjing. Thanks for reaching out. We will shortly update the codes so you can find our methods used to generate the noise data from the figure.

**Comment by ycjing** [comment]
Hi @superlouis 

Thank you for the quick response! I truly appreciate it. Look forward to your updated code soon!

Cheers,
Yongcheng

**Comment by superlouis** [comment]
@ycjing I just updated the codes. They should now reflect the requested functionality for modifying the graphs with noise (pseudo-nodes and edges).
